# Generated by Django 5.0 on 2024-12-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=72),
        ),
    ]
